name: Tag on Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calc_tag
        run: |
          if [ -z "$TAG" ]; then
            NEXT_TAG="v0.0.1"
          else
            IFS='.' read -r -a parts <<< "${TAG#v}"
            major="${parts[0]}"
            minor="${parts[1]}"
            patch="${parts[2]}"
          
            patch=$((patch + 1))
          
            if [ $patch -eq 100 ]; then
              patch=0
              minor=$((minor + 1))
            fi
          
            NEXT_TAG="v${major}.${minor}.${patch}"
          fi
          echo "Next tag: $NEXT_TAG"
          echo "next_tag=$NEXT_TAG" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag ${{ env.next_tag }}
          git push origin ${{ env.next_tag }}

      - name: Output Tag
        run: echo "Tag ${{ env.next_tag }} created and pushed successfully."
